adds neccessary linter
Teshager21/members-only pull request #1
Opened 2020-07-09 16:47 UTC by Teshager21

start the linters

2020-07-14 07:09 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Nice job :clap: 
However, There some missing requirements.

1. According to [that](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png), your PR must have a title and a description

2. Read the comment left below

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-14 07:09 UTC, maelfosso commented on app/views/posts/index.html.erb
> +    <%if post.user && signed_in?%>
use a view helper for that.

2020-07-14 07:09 UTC, maelfosso commented on app/views/layouts/application.html.erb
> +      <%end%>
Use a view helper for that `if/else` block

2020-07-14 21:26 UTC, uche-inyama requested changes
## Changes required

Hi team :wave: 

Kindly remove the commented code between lines 5 and 7 of posts/index.html.erb.

When you are done with this change, submit another


#### ``` Have a great day```

``` Uchechukwu Inyama Henry ``` form for a code.

2020-07-14 21:26 UTC, uche-inyama commented on app/views/posts/index.html.erb
> +    <%end %>  -->
Remove commented code.

2020-07-15 07:43 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the changes 
You can merge it :+1: 

Good continuation :handshake: 

Mael FOSSO

2020-07-15 08:26 UTC, merged